# Site settings
title: Jakub Krajcovic
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

collections:
  project:
    output: true

defaults:
  - scope:
      path: ""
      type: project
    values:
      layout: project
